### ISSUE TITLE
The release notes for 7.10.2 state that it was compiled against `linux-headers-3.1`.

### ISSUE THREAD

**Issue by noteed** [redneb/ghc-alt-libc#1]
The release notes for 7.10.2 state that it was compiled against `linux-headers-3.1`. I guess it should be `linux-headers-3.16`.

https://github.com/redneb/ghc-alt-libc/blob/master/NOTES-musl.md

**Comment by redneb** [comment]
There is actually no typo. I am using an old version of linux headers in my musl environment because it will make statically linked binaries even more portable. When compiling GHC, that shouldn't make any difference as GHC does not seem to use any of the syscalls that were recently added to the kernel.
